"""Catalogue seed data — a direct port of the Laravel seeders.

Pill order matches the reference design: All Categories / Deals are handled in
the UI, the rest are real categories.
"""

from __future__ import annotations

CATEGORIES: list[dict] = [
    {"name": "Crypto", "slug": "crypto", "emoji": "₿"},
    {"name": "Fashion", "slug": "fashion", "emoji": "👗"},
    {"name": "Health & Wellness", "slug": "health-wellness", "emoji": "🧘"},
    {"name": "Art", "slug": "art", "emoji": "🎨"},
    {"name": "Home", "slug": "home", "emoji": "🏠"},
    {"name": "Sport", "slug": "sport", "emoji": "⚽"},
    {"name": "Music", "slug": "music", "emoji": "🎵"},
    {"name": "Gaming", "slug": "gaming", "emoji": "🎮"},
]

BRANDS: list[dict] = [
    {"name": "Adidas", "slug": "adidas", "initials": "AD", "color": "#111827"},
    {"name": "Asics", "slug": "asics", "initials": "AS", "color": "#1d4ed8"},
    {"name": "Columbia", "slug": "columbia", "initials": "CO", "color": "#2563eb"},
    {"name": "Demix", "slug": "demix", "initials": "DM", "color": "#0d9488"},
    {"name": "New Balance", "slug": "new-balance", "initials": "NB", "color": "#dc2626"},
    {"name": "Nike", "slug": "nike", "initials": "NK", "color": "#f97316"},
    {"name": "Under Armour", "slug": "under-armour", "initials": "UA", "color": "#475569"},
    {"name": "Wilson", "slug": "wilson", "initials": "WI", "color": "#e11d48"},
    {"name": "Xiaomi", "slug": "xiaomi", "initials": "XI", "color": "#ff6900"},
    {"name": "Yonex", "slug": "yonex", "initials": "YO", "color": "#16a34a"},
]

PRODUCTS: list[dict] = [
    # ------------------------------------------------------------------ Sport
    {
        "name": "Smart Watch WH22-6 Fitness Tracker",
        "category": "sport",
        "brand": "xiaomi",
        "emoji": "⌚",
        "price": 454.00,
        "badge": "top",
        "rating": 4.80,
        "reviews": 126,
        "options": {"sizes": ["41mm", "45mm"], "colors": ["Silver", "Midnight"]},
        "description": "Always-on retina display, 7-day battery, heart-rate and sleep tracking with 100+ sport modes.",
    },
    {
        "name": "Tennis Rackets for Beginners",
        "category": "sport",
        "brand": "wilson",
        "emoji": "🎾",
        "price": 30.99,
        "rating": 4.50,
        "reviews": 84,
        "description": "Lightweight graphite frame with a generous sweet spot — the perfect first racket for court newcomers.",
    },
    {
        "name": "Premium Boxing Gloves for Pro Training",
        "category": "sport",
        "brand": "adidas",
        "emoji": "🥊",
        "price": 196.84,
        "compare": 276.57,
        "is_deal": True,
        "rating": 4.70,
        "reviews": 212,
        "options": {"sizes": ["12 oz", "14 oz", "16 oz"], "colors": ["White", "Black"]},
        "description": "Multi-layer foam padding with a locked-in wrist wrap, built for heavy bag and sparring sessions.",
    },
    {
        "name": "Club Kit 1 Recurve Archery Bow",
        "category": "sport",
        "brand": "demix",
        "emoji": "🏹",
        "price": 48.99,
        "rating": 4.40,
        "reviews": 57,
        "description": "Complete recurve starter kit with riser, limbs, string and finger tab — takedown design for easy transport.",
    },
    {
        "name": "Lightweight White Nike Training Shoes",
        "category": "sport",
        "brand": "nike",
        "emoji": "👟",
        "price": 210.00,
        "badge": "top",
        "rating": 4.60,
        "reviews": 340,
        "options": {"sizes": ["7", "8", "9", "10", "11"], "colors": ["White", "Grey"]},
        "description": "Breathable mesh upper with responsive foam cushioning for training days and everyday miles.",
    },
    {
        "name": "Pro Grip Badminton Shuttlecocks (12 Pack)",
        "category": "sport",
        "brand": "yonex",
        "emoji": "🏸",
        "price": 12.99,
        "rating": 4.30,
        "reviews": 45,
        "description": "Tournament-grade feather shuttlecocks with consistent flight and durable cork bases.",
    },
    {
        "name": "Adidas Training Duffel Bag",
        "category": "sport",
        "brand": "adidas",
        "emoji": "🎒",
        "price": 64.50,
        "rating": 4.50,
        "reviews": 98,
        "description": "30L gym duffel with ventilated shoe pocket, water-resistant base and adjustable padded strap.",
    },
    {
        "name": "Asics Gel Quantum Running Shoes",
        "category": "sport",
        "brand": "asics",
        "emoji": "👟",
        "price": 139.99,
        "compare": 179.99,
        "is_deal": True,
        "rating": 4.60,
        "reviews": 154,
        "options": {"sizes": ["7", "8", "9", "10", "11"], "colors": ["Silver", "Navy"]},
        "description": "GEL® cushioning in the rearfoot and a springy midsole for long, comfortable road runs.",
    },
    {
        "name": "Adjustable Dumbbell Set 20 kg",
        "category": "sport",
        "brand": "demix",
        "emoji": "🏋️",
        "price": 189.00,
        "rating": 4.80,
        "reviews": 76,
        "delivery_standard": True,
        "delivery_pickup": False,
        "description": "Space-saving adjustable dumbbells from 2.5 kg to 20 kg with quick-select dial locks.",
    },
    # ---------------------------------------------------------------- Fashion
    {
        "name": "Nike White Thermo-Fit Pullover Training Hoodie",
        "category": "fashion",
        "brand": "nike",
        "emoji": "🧥",
        "price": 154.95,
        "featured": True,
        "rating": 4.70,
        "reviews": 412,
        "chips": [4.7, 4.4, 5.0],
        "options": {"sizes": ["S", "M", "L", "XL"], "colors": ["White", "Black", "Purple"]},
        "description": "Thermal knit that traps heat without the bulk — thumbholes, a cross-zip neck and reflective details for cold-weather sessions.",
    },
    {
        "name": "Columbia Rapid Shield Windbreaker",
        "category": "fashion",
        "brand": "columbia",
        "emoji": "🧥",
        "price": 89.99,
        "rating": 4.50,
        "reviews": 187,
        "options": {"sizes": ["S", "M", "L", "XL"], "colors": ["Blue", "Olive"]},
        "description": "Fully seam-sealed, packable windbreaker with an adjustable storm hood.",
    },
    {
        "name": "Adidas Originals Graphic Tee",
        "category": "fashion",
        "brand": "adidas",
        "emoji": "👚",
        "price": 34.99,
        "compare": 44.99,
        "is_deal": True,
        "rating": 4.40,
        "reviews": 260,
        "options": {"sizes": ["S", "M", "L", "XL"], "colors": ["White", "Black"]},
        "description": "Soft cotton jersey tee with a vintage trefoil graphic and relaxed fit.",
    },
    {
        "name": "New Balance 574 Classic Sneakers",
        "category": "fashion",
        "brand": "new-balance",
        "emoji": "👟",
        "price": 119.00,
        "rating": 4.70,
        "reviews": 305,
        "options": {"sizes": ["7", "8", "9", "10", "11"], "colors": ["Grey", "Navy"]},
        "description": "The timeless 80s runner with ENCAP midsole cushioning and suede overlays.",
    },
    {
        "name": "Asics Sportstyle Running Cap",
        "category": "fashion",
        "brand": "asics",
        "emoji": "🧢",
        "price": 24.50,
        "rating": 4.20,
        "reviews": 66,
        "description": "Ultralight ventilated cap with a moisture-wicking sweatband and adjustable back closure.",
    },
    {
        "name": "Columbia Steens Fleece Pullover",
        "category": "fashion",
        "brand": "columbia",
        "emoji": "🧣",
        "price": 74.00,
        "rating": 4.60,
        "reviews": 141,
        "options": {"sizes": ["S", "M", "L", "XL"], "colors": ["Charcoal", "Sand"]},
        "description": "Plush microfleece pullover with a full-zip chest pocket — an everyday layering staple.",
    },
    # ------------------------------------------------------- Health & Wellness
    {
        "name": "Xiaomi Mi Smart Body Scale",
        "category": "health-wellness",
        "brand": "xiaomi",
        "emoji": "⚖️",
        "price": 42.00,
        "rating": 4.50,
        "reviews": 198,
        "description": "13 essential body metrics with app sync, high-precision sensors and a crisp LED display.",
    },
    {
        "name": "Aroma Mist Diffuser Lamp",
        "category": "health-wellness",
        "emoji": "🕯️",
        "price": 36.90,
        "rating": 4.60,
        "reviews": 132,
        "description": "Warm wood-grain diffuser with a dimmable lamp, colour modes and auto shut-off.",
    },
    {
        "name": "Resistance Bands Set (5 Pieces)",
        "category": "health-wellness",
        "brand": "demix",
        "emoji": "🧘",
        "price": 21.99,
        "compare": 29.99,
        "is_deal": True,
        "rating": 4.30,
        "reviews": 221,
        "description": "Five looped bands from extra-light to extra-heavy, with a carry bag and exercise guide.",
    },
    {
        "name": "Insulated Steel Water Bottle 750ml",
        "category": "health-wellness",
        "emoji": "🥤",
        "price": 27.50,
        "rating": 4.70,
        "reviews": 410,
        "options": {"colors": ["Steel", "Violet", "Black"]},
        "description": "Double-wall vacuum insulation keeps drinks cold for 24 hours, leak-proof sport cap.",
    },
    # ------------------------------------------------------------------- Home
    {
        "name": "Minimalist LED Desk Lamp",
        "category": "home",
        "emoji": "💡",
        "price": 58.00,
        "rating": 4.60,
        "reviews": 89,
        "description": "Flicker-free LED bar with five colour temperatures, touch dimming and a USB-C charging port.",
    },
    {
        "name": "Ceramic Nonstick Cookware Set (5 pc)",
        "category": "home",
        "emoji": "🍳",
        "price": 149.00,
        "rating": 4.50,
        "reviews": 74,
        "delivery_standard": True,
        "delivery_pickup": False,
        "description": "PFAS-free ceramic coating, even-heat aluminium bodies, oven safe up to 200°C.",
    },
    {
        "name": "Cozy Knit Throw Blanket",
        "category": "home",
        "emoji": "🛋️",
        "price": 39.99,
        "compare": 52.99,
        "is_deal": True,
        "rating": 4.70,
        "reviews": 166,
        "description": "Chunky cable-knit throw in brushed microfibre — machine washable and sofa-ready.",
    },
    {
        "name": "Botanical Scented Candle Trio",
        "category": "home",
        "emoji": "🪔",
        "price": 26.00,
        "rating": 4.40,
        "reviews": 95,
        "description": "Three soy-wax candles — eucalyptus, lavender and sea salt — with a 40-hour burn each.",
    },
    # ------------------------------------------------------------------ Music
    {
        "name": "Wireless Studio Headphones Pro",
        "category": "music",
        "brand": "xiaomi",
        "emoji": "🎧",
        "price": 129.00,
        "badge": "top",
        "featured": True,
        "rating": 4.80,
        "reviews": 512,
        "chips": [4.8, 4.6, 5.0],
        "options": {"colors": ["Black", "White"]},
        "description": "Hybrid ANC, 40-hour battery and studio-tuned 40mm drivers with multipoint Bluetooth.",
    },
    {
        "name": "Acoustic Guitar Starter Kit",
        "category": "music",
        "emoji": "🎸",
        "price": 199.00,
        "rating": 4.60,
        "reviews": 63,
        "delivery_standard": True,
        "delivery_pickup": False,
        "description": "Full-size dreadnought with solid spruce top, gig bag, tuner and spare strings.",
    },
    {
        "name": "Portable Bluetooth Speaker Splashproof",
        "category": "music",
        "brand": "xiaomi",
        "emoji": "🔊",
        "price": 79.99,
        "compare": 99.99,
        "is_deal": True,
        "rating": 4.50,
        "reviews": 287,
        "description": "IPX7 waterproof speaker with deep dual drivers, 24-hour playtime and stereo pairing.",
    },
    # ----------------------------------------------------------------- Gaming
    {
        "name": "RGB Mechanical Gaming Keyboard",
        "category": "gaming",
        "emoji": "⌨️",
        "price": 89.00,
        "rating": 4.70,
        "reviews": 331,
        "options": {"colors": ["Black", "White"]},
        "description": "Hot-swappable switches, per-key RGB, detachable USB-C cable and a machined aluminium top plate.",
    },
    {
        "name": "Pro Wireless Controller Gamepad",
        "category": "gaming",
        "emoji": "🎮",
        "price": 69.00,
        "rating": 4.60,
        "reviews": 402,
        "description": "Low-latency 2.4 GHz wireless pad with remappable back paddles and hall-effect sticks.",
    },
    {
        "name": "Ultralight Gaming Mouse 8K",
        "category": "gaming",
        "emoji": "🖱️",
        "price": 49.00,
        "compare": 59.00,
        "is_deal": True,
        "rating": 4.50,
        "reviews": 178,
        "description": "58-gram honeycomb shell, 30K optical sensor and an 8000 Hz polling receiver in the box.",
    },
    # -------------------------------------------------------------------- Art
    {
        "name": "Watercolor Paint Set 36 Colors",
        "category": "art",
        "emoji": "🎨",
        "price": 27.50,
        "rating": 4.40,
        "reviews": 118,
        "description": "Highly pigmented pans with a folding palette, water brush and mixing tray.",
    },
    {
        "name": "Adjustable Wooden Canvas Easel",
        "category": "art",
        "emoji": "🖼️",
        "price": 55.00,
        "rating": 4.50,
        "reviews": 52,
        "delivery_standard": True,
        "delivery_pickup": False,
        "description": "Beechwood H-frame easel that folds flat, holding canvases up to 100 cm.",
    },
    # ----------------------------------------------------------------- Crypto
    {
        "name": "Secure Element Hardware Wallet",
        "category": "crypto",
        "emoji": "🔐",
        "price": 79.00,
        "rating": 4.80,
        "reviews": 94,
        "description": "Open-source firmware, EAL6+ secure element and a bright touchscreen for on-device verification.",
    },
    {
        "name": "Crypto Trader Enamel Mug",
        "category": "crypto",
        "emoji": "☕",
        "price": 14.99,
        "compare": 19.99,
        "is_deal": True,
        "rating": 4.30,
        "reviews": 205,
        "description": "Double-fired enamel mug with a diamond-glaze finish — dishwasher safe, laser etched chart line.",
    },
]

# slug -> list of (author, avatar, rating, comment, days_ago)
REVIEWS: dict[str, list[tuple]] = {
    "nike-white-thermo-fit-pullover-training-hoodie": [
        ("Maya R.", "👩🏽", 5, "The thermo fabric is seriously warm without feeling heavy. Sized up for layering — perfect.", 6),
        ("Tom K.", "🧑🏻", 4, "Great fit and the zip neck keeps the wind out. Wish it had a hood pocket.", 14),
        ("Zara A.", "👩🏻", 5, "Third Nike hoodie, still my favourite. The white colour has not yellowed after washing.", 22),
    ],
    "smart-watch-wh22-6-fitness-tracker": [
        ("Leo P.", "🧑🏿", 5, "Battery genuinely lasts a week and the sleep tracking is spot on.", 3),
        ("Ines G.", "👩🏼", 5, "Bought it for running — GPS lock is fast and the display stays readable in sun.", 11),
        ("Ravi S.", "🧑🏾", 4, "Great watch for the money. Strap could be softer out of the box.", 19),
    ],
    "lightweight-white-nike-training-shoes": [
        ("Chloe M.", "👩🏼", 5, "Light as a feather, zero break-in period. Ordered a second pair.", 5),
        ("Dmitri V.", "🧑🏻", 4, "Snug fit — go half a size up if you have wide feet.", 12),
    ],
    "premium-boxing-gloves-for-pro-training": [
        ("Coach Ray", "🧑🏿", 5, "Wrist support is excellent for bag work. Padding holds up after months.", 8),
        ("Amina B.", "👩🏽", 4, "Comfortable, but the closure strap runs a little long.", 17),
    ],
    "wireless-studio-headphones-pro": [
        ("SoundCheck", "🧑🏻", 5, "ANC kills the office hum completely. Multipoint with laptop + phone just works.", 4),
        ("Jules D.", "👩🏿", 5, "Forty hours is not a typo — I charge these once a week.", 9),
        ("Pete H.", "🧑🏼", 4, "Bass is warm, app EQ could be more detailed.", 15),
    ],
    "club-kit-1-recurve-archery-bow": [
        ("ArcheryNate", "🧑🏼", 4, "Solid starter bow, smooth draw. Arrows are basic but you outgrow them fast.", 13),
        ("Kim L.", "👩🏻", 5, "Set up in ten minutes, groups tightened up quickly.", 25),
    ],
    "tennis-rackets-for-beginners": [
        ("FirstServe", "🧑🏿", 4, "Light and forgiving — exactly what a beginner needs.", 7),
        ("Ella T.", "👩🏼", 5, "Grip swaps easily, my coach approved.", 21),
    ],
    "new-balance-574-classic-sneakers": [
        ("Marco B.", "🧑🏻", 5, "The grey colourway goes with everything. True to size.", 10),
        ("Nia W.", "👩🏾", 4, "Comfortable all day, slight width in the toe box.", 18),
    ],
}
